import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "sonner";
import MySessionProvider from "@/MySessionProvider/MySessionProvider";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import CartContextProvider from "@/Context/cartContext";
import WishlistContextProvider from "@/Context/wishlistContext";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="E:\Web\Front-end Diploma\Assignments\React\E-commerce\e-commerce\public\rMXM_J0hBtPS.jpg"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <WishlistContextProvider>
            <CartContextProvider>
              <Toaster richColors />
              <Navbar />
              {children}
            </CartContextProvider>
          </WishlistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
